all: android contacts sms device whitelist splashscreen

android:
	ionic platform add android

contacts:
	cordova plugin add org.apache.cordova.contacts

sms:
	cordova plugin add cordova-plugin-sms
	
device:
	cordova plugin add org.apache.cordova.device
	
whitelist:
	cordova plugin add cordova-plugin-whitelist

splashscreen:
	cordova plugin add cordova-plugin-splashscreen
